FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
RUN pip install deepface==0.0.78
RUN pip install fastapi==0.95.1

RUN pip install pytest
RUN pip install httpx

COPY ./backend/requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY ./backend ./backend
COPY ./tests ./tests

EXPOSE 8000

ENTRYPOINT ["pytest"]
