FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git
RUN pip install git+https://github.com/Asterios7/dlib-wrapper.git

RUN pip install pytest
RUN pip install httpx

COPY ./backend/requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

COPY ./backend ./backend
COPY ./tests ./tests

EXPOSE 8000

ENTRYPOINT ["pytest"]
