version: "3"

services:
  # Backend 
  fastapi-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    env_file:
      - .env
    ports:
      - 8000:8000
  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit-app
    environment:
      TOKEN_KEY: 'shouldbeverysecure'
    ports:
      - 8501:8501
    volumes:
      - type: bind
        source: ./frontend
        target: /app
