version: "3"

services:
  # Backend 
  fastapi-app:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - 8000:8000
    # volumes:
    #   - type: bind
    #     source: ./backend
    #     target: /app
  # Frontend
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit-app
    environment:
      BACKEND_ADDRESS: "fastapi-app:8000"
    ports:
      - 8501:8501
