version: "3"

services:
  # Backend 
  fastapi-app:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-app
    env_file:
      - .env
    ports:
      - 8000:8000
  # Frontend
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: streamlit-app
    environment:
      BACKEND_ADDRESS: "fastapi-app:8000"
    ports:
      - 8501:8501
    volumes:
      - type: bind
        source: ./frontend
        target: /app
