name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container:

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: bash run_tests.sh
